name: CICD
run-name: Running CI-CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: go.sum

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...